### PR TITLE
Simplify the implementation

### PR DESCRIPTION
**Pull request by tomekw**
:)

### CODE REVIEW

**Comment by RadekMolenda** [comment]
:100:

**Comment by RadekMolenda** [comment]
specs?

**Comment by tomekw** [comment]
@RadekMolenda https://github.com/ruby/spec/blob/master/core/string/rjust_spec.rb

**Comment by tomekw** [comment]
@Somsubhra improvement idea, open the `String` class and do `alias_method :left_pad, :rjust` :)

**Comment by Somsubhra** [comment]
Thanks for the patch @tomekw. I like your suggestion to use `alias_method`.

**Comment by tomekw** [comment]
@Somsubhra my point is - if the `left-pad` is not a joke, then you don't need it at all, Ruby stdlib has `rjust` on String and it does exactly what you want :)

**Comment by Somsubhra** [comment]
TBH...
... it's a joke :stuck_out_tongue:

**Pull request merged**
